name: JPacman CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 11 (or JDK 17 if needed)
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configure Gradle with a specific version
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
      with:
        gradle-version: '7.5' # Specify the Gradle version you want to use

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: xvfb-run ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Generate and submit dependency graph for Dependabot Alerts
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.0.0
